{"level":30,"time":1674668992092,"pid":66535,"hostname":"flow-Precision-5560","msg":"Parameters not found: email,"}
{"level":30,"time":1690685021677,"pid":33212,"hostname":"flow-Precision-5560","msg":"Error trying to login user"}
{"level":50,"time":1690685021677,"pid":33212,"hostname":"flow-Precision-5560","err":{"type":"TypeError","message":"Cannot read properties of null (reading 'dataValues')","stack":"TypeError: Cannot read properties of null (reading 'dataValues')\n    at Object.login (/home/flow/dev/fede/app_turnos_js/src/infrastructure/services/dbAuthService.js:37:55)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async login (/home/flow/dev/fede/app_turnos_js/src/domain/services/authService.js:78:26)"},"msg":"Cannot read properties of null (reading 'dataValues')"}
{"level":30,"time":1690685029710,"pid":33212,"hostname":"flow-Precision-5560","msg":"Error trying to login user"}
{"level":50,"time":1690685029710,"pid":33212,"hostname":"flow-Precision-5560","err":{"type":"TypeError","message":"Cannot read properties of null (reading 'dataValues')","stack":"TypeError: Cannot read properties of null (reading 'dataValues')\n    at Object.login (/home/flow/dev/fede/app_turnos_js/src/infrastructure/services/dbAuthService.js:37:55)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async login (/home/flow/dev/fede/app_turnos_js/src/domain/services/authService.js:78:26)"},"msg":"Cannot read properties of null (reading 'dataValues')"}
{"level":30,"time":1691341173933,"pid":18346,"hostname":"flow-Precision-5560","msg":"(dbGetUserByEmail): Error trying to find user by email"}
{"level":50,"time":1691341173934,"pid":18346,"hostname":"flow-Precision-5560","err":{"type":"DatabaseError","message":"Unknown column 'street' in 'field list'","stack":"Error\n    at Query.run (/home/flow/dev/fede/app_turnos_js/node_modules/sequelize/lib/dialects/mysql/query.js:52:25)\n    at /home/flow/dev/fede/app_turnos_js/node_modules/sequelize/lib/sequelize.js:314:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async MySQLQueryInterface.select (/home/flow/dev/fede/app_turnos_js/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:12)\n    at async Customer.findAll (/home/flow/dev/fede/app_turnos_js/node_modules/sequelize/lib/model.js:1134:21)\n    at async Customer.findOne (/home/flow/dev/fede/app_turnos_js/node_modules/sequelize/lib/model.js:1228:12)\n    at async Object.dbGetUserByEmail (/home/flow/dev/fede/app_turnos_js/src/infrastructure/services/dbAuthService.js:80:20)\n    at async validateUserExists (/home/flow/dev/fede/app_turnos_js/src/domain/services/authService.js:197:16)\n    at async signup (/home/flow/dev/fede/app_turnos_js/src/domain/services/authService.js:28:30)","name":"SequelizeDatabaseError","parent":{"type":"Error","message":"Unknown column 'street' in 'field list'","stack":"Error: Unknown column 'street' in 'field list'\n    at Packet.asError (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/packets/packet.js:728:17)\n    at Query.execute (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/commands/command.js:29:26)\n    at Connection.handlePacket (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/connection.js:456:32)\n    at PacketParser.onPacket (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/connection.js:85:12)\n    at PacketParser.executeStart (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/packet_parser.js:75:16)\n    at Socket.<anonymous> (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/connection.js:92:25)\n    at Socket.emit (node:events:513:28)\n    at addChunk (node:internal/streams/readable:324:12)\n    at readableAddChunk (node:internal/streams/readable:297:9)\n    at Readable.push (node:internal/streams/readable:234:10)","code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'street' in 'field list'","sql":"SELECT `id`, `name`, `lastname`, `email`, `password`, `id_number`, `street`, `street_number`, `city`, `country`, `phone`, `created_at`, `updated_at`, `deleted_at` FROM `customers` AS `Customer` WHERE (`Customer`.`deleted_at` IS NULL AND `Customer`.`email` = 'fedegarcia222@gmail.com') LIMIT 1;"},"original":{"type":"Error","message":"Unknown column 'street' in 'field list'","stack":"Error: Unknown column 'street' in 'field list'\n    at Packet.asError (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/packets/packet.js:728:17)\n    at Query.execute (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/commands/command.js:29:26)\n    at Connection.handlePacket (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/connection.js:456:32)\n    at PacketParser.onPacket (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/connection.js:85:12)\n    at PacketParser.executeStart (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/packet_parser.js:75:16)\n    at Socket.<anonymous> (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/connection.js:92:25)\n    at Socket.emit (node:events:513:28)\n    at addChunk (node:internal/streams/readable:324:12)\n    at readableAddChunk (node:internal/streams/readable:297:9)\n    at Readable.push (node:internal/streams/readable:234:10)","code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'street' in 'field list'","sql":"SELECT `id`, `name`, `lastname`, `email`, `password`, `id_number`, `street`, `street_number`, `city`, `country`, `phone`, `created_at`, `updated_at`, `deleted_at` FROM `customers` AS `Customer` WHERE (`Customer`.`deleted_at` IS NULL AND `Customer`.`email` = 'fedegarcia222@gmail.com') LIMIT 1;"},"sql":"SELECT `id`, `name`, `lastname`, `email`, `password`, `id_number`, `street`, `street_number`, `city`, `country`, `phone`, `created_at`, `updated_at`, `deleted_at` FROM `customers` AS `Customer` WHERE (`Customer`.`deleted_at` IS NULL AND `Customer`.`email` = 'fedegarcia222@gmail.com') LIMIT 1;","parameters":{}},"msg":"Unknown column 'street' in 'field list'"}
{"level":30,"time":1691341218821,"pid":18585,"hostname":"flow-Precision-5560","msg":"(dbGetUserByEmail): Error trying to find user by email"}
{"level":50,"time":1691341218821,"pid":18585,"hostname":"flow-Precision-5560","err":{"type":"DatabaseError","message":"Unknown column 'street' in 'field list'","stack":"Error\n    at Query.run (/home/flow/dev/fede/app_turnos_js/node_modules/sequelize/lib/dialects/mysql/query.js:52:25)\n    at /home/flow/dev/fede/app_turnos_js/node_modules/sequelize/lib/sequelize.js:314:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async MySQLQueryInterface.select (/home/flow/dev/fede/app_turnos_js/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:12)\n    at async Customer.findAll (/home/flow/dev/fede/app_turnos_js/node_modules/sequelize/lib/model.js:1134:21)\n    at async Customer.findOne (/home/flow/dev/fede/app_turnos_js/node_modules/sequelize/lib/model.js:1228:12)\n    at async Object.dbGetUserByEmail (/home/flow/dev/fede/app_turnos_js/src/infrastructure/services/dbAuthService.js:70:20)\n    at async validateUserExists (/home/flow/dev/fede/app_turnos_js/src/domain/services/authService.js:197:16)\n    at async signup (/home/flow/dev/fede/app_turnos_js/src/domain/services/authService.js:28:30)","name":"SequelizeDatabaseError","parent":{"type":"Error","message":"Unknown column 'street' in 'field list'","stack":"Error: Unknown column 'street' in 'field list'\n    at Packet.asError (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/packets/packet.js:728:17)\n    at Query.execute (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/commands/command.js:29:26)\n    at Connection.handlePacket (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/connection.js:456:32)\n    at PacketParser.onPacket (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/connection.js:85:12)\n    at PacketParser.executeStart (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/packet_parser.js:75:16)\n    at Socket.<anonymous> (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/connection.js:92:25)\n    at Socket.emit (node:events:513:28)\n    at addChunk (node:internal/streams/readable:324:12)\n    at readableAddChunk (node:internal/streams/readable:297:9)\n    at Readable.push (node:internal/streams/readable:234:10)","code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'street' in 'field list'","sql":"SELECT `id`, `name`, `lastname`, `email`, `password`, `id_number`, `street`, `street_number`, `city`, `country`, `phone`, `created_at`, `updated_at`, `deleted_at` FROM `customers` AS `Customer` WHERE (`Customer`.`deleted_at` IS NULL AND `Customer`.`email` = 'fedegarcia222@gmail.com') LIMIT 1;"},"original":{"type":"Error","message":"Unknown column 'street' in 'field list'","stack":"Error: Unknown column 'street' in 'field list'\n    at Packet.asError (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/packets/packet.js:728:17)\n    at Query.execute (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/commands/command.js:29:26)\n    at Connection.handlePacket (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/connection.js:456:32)\n    at PacketParser.onPacket (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/connection.js:85:12)\n    at PacketParser.executeStart (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/packet_parser.js:75:16)\n    at Socket.<anonymous> (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/connection.js:92:25)\n    at Socket.emit (node:events:513:28)\n    at addChunk (node:internal/streams/readable:324:12)\n    at readableAddChunk (node:internal/streams/readable:297:9)\n    at Readable.push (node:internal/streams/readable:234:10)","code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'street' in 'field list'","sql":"SELECT `id`, `name`, `lastname`, `email`, `password`, `id_number`, `street`, `street_number`, `city`, `country`, `phone`, `created_at`, `updated_at`, `deleted_at` FROM `customers` AS `Customer` WHERE (`Customer`.`deleted_at` IS NULL AND `Customer`.`email` = 'fedegarcia222@gmail.com') LIMIT 1;"},"sql":"SELECT `id`, `name`, `lastname`, `email`, `password`, `id_number`, `street`, `street_number`, `city`, `country`, `phone`, `created_at`, `updated_at`, `deleted_at` FROM `customers` AS `Customer` WHERE (`Customer`.`deleted_at` IS NULL AND `Customer`.`email` = 'fedegarcia222@gmail.com') LIMIT 1;","parameters":{}},"msg":"Unknown column 'street' in 'field list'"}
{"level":30,"time":1691341351191,"pid":18964,"hostname":"flow-Precision-5560","msg":"(dbGetUserByEmail): Error trying to find user by email"}
{"level":50,"time":1691341351191,"pid":18964,"hostname":"flow-Precision-5560","err":{"type":"DatabaseError","message":"Unknown column 'street' in 'field list'","stack":"Error\n    at Query.run (/home/flow/dev/fede/app_turnos_js/node_modules/sequelize/lib/dialects/mysql/query.js:52:25)\n    at /home/flow/dev/fede/app_turnos_js/node_modules/sequelize/lib/sequelize.js:314:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async MySQLQueryInterface.select (/home/flow/dev/fede/app_turnos_js/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:12)\n    at async Customer.findAll (/home/flow/dev/fede/app_turnos_js/node_modules/sequelize/lib/model.js:1134:21)\n    at async Customer.findOne (/home/flow/dev/fede/app_turnos_js/node_modules/sequelize/lib/model.js:1228:12)\n    at async Object.dbGetUserByEmail (/home/flow/dev/fede/app_turnos_js/src/infrastructure/services/dbAuthService.js:66:20)\n    at async validateUserExists (/home/flow/dev/fede/app_turnos_js/src/domain/services/authService.js:197:16)\n    at async signup (/home/flow/dev/fede/app_turnos_js/src/domain/services/authService.js:28:30)","name":"SequelizeDatabaseError","parent":{"type":"Error","message":"Unknown column 'street' in 'field list'","stack":"Error: Unknown column 'street' in 'field list'\n    at Packet.asError (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/packets/packet.js:728:17)\n    at Query.execute (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/commands/command.js:29:26)\n    at Connection.handlePacket (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/connection.js:456:32)\n    at PacketParser.onPacket (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/connection.js:85:12)\n    at PacketParser.executeStart (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/packet_parser.js:75:16)\n    at Socket.<anonymous> (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/connection.js:92:25)\n    at Socket.emit (node:events:513:28)\n    at addChunk (node:internal/streams/readable:324:12)\n    at readableAddChunk (node:internal/streams/readable:297:9)\n    at Readable.push (node:internal/streams/readable:234:10)","code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'street' in 'field list'","sql":"SELECT `id`, `name`, `lastname`, `email`, `password`, `id_number`, `street`, `street_number`, `city`, `country`, `phone`, `created_at`, `updated_at`, `deleted_at` FROM `customers` AS `Customer` WHERE (`Customer`.`deleted_at` IS NULL AND `Customer`.`email` = 'fedegarcia222@gmail.com') LIMIT 1;"},"original":{"type":"Error","message":"Unknown column 'street' in 'field list'","stack":"Error: Unknown column 'street' in 'field list'\n    at Packet.asError (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/packets/packet.js:728:17)\n    at Query.execute (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/commands/command.js:29:26)\n    at Connection.handlePacket (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/connection.js:456:32)\n    at PacketParser.onPacket (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/connection.js:85:12)\n    at PacketParser.executeStart (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/packet_parser.js:75:16)\n    at Socket.<anonymous> (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/connection.js:92:25)\n    at Socket.emit (node:events:513:28)\n    at addChunk (node:internal/streams/readable:324:12)\n    at readableAddChunk (node:internal/streams/readable:297:9)\n    at Readable.push (node:internal/streams/readable:234:10)","code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'street' in 'field list'","sql":"SELECT `id`, `name`, `lastname`, `email`, `password`, `id_number`, `street`, `street_number`, `city`, `country`, `phone`, `created_at`, `updated_at`, `deleted_at` FROM `customers` AS `Customer` WHERE (`Customer`.`deleted_at` IS NULL AND `Customer`.`email` = 'fedegarcia222@gmail.com') LIMIT 1;"},"sql":"SELECT `id`, `name`, `lastname`, `email`, `password`, `id_number`, `street`, `street_number`, `city`, `country`, `phone`, `created_at`, `updated_at`, `deleted_at` FROM `customers` AS `Customer` WHERE (`Customer`.`deleted_at` IS NULL AND `Customer`.`email` = 'fedegarcia222@gmail.com') LIMIT 1;","parameters":{}},"msg":"Unknown column 'street' in 'field list'"}
{"level":30,"time":1691341474341,"pid":19172,"hostname":"flow-Precision-5560","msg":"(dbGetUserByEmail): Error trying to find user by email"}
{"level":50,"time":1691341474341,"pid":19172,"hostname":"flow-Precision-5560","err":{"type":"DatabaseError","message":"Unknown column 'street' in 'field list'","stack":"Error\n    at Query.run (/home/flow/dev/fede/app_turnos_js/node_modules/sequelize/lib/dialects/mysql/query.js:52:25)\n    at /home/flow/dev/fede/app_turnos_js/node_modules/sequelize/lib/sequelize.js:314:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async MySQLQueryInterface.select (/home/flow/dev/fede/app_turnos_js/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:12)\n    at async Customer.findAll (/home/flow/dev/fede/app_turnos_js/node_modules/sequelize/lib/model.js:1134:21)\n    at async Customer.findOne (/home/flow/dev/fede/app_turnos_js/node_modules/sequelize/lib/model.js:1228:12)\n    at async Object.dbGetUserByEmail (/home/flow/dev/fede/app_turnos_js/src/infrastructure/services/dbAuthService.js:66:20)\n    at async validateUserExists (/home/flow/dev/fede/app_turnos_js/src/domain/services/authService.js:197:16)\n    at async signup (/home/flow/dev/fede/app_turnos_js/src/domain/services/authService.js:28:30)","name":"SequelizeDatabaseError","parent":{"type":"Error","message":"Unknown column 'street' in 'field list'","stack":"Error: Unknown column 'street' in 'field list'\n    at Packet.asError (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/packets/packet.js:728:17)\n    at Query.execute (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/commands/command.js:29:26)\n    at Connection.handlePacket (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/connection.js:456:32)\n    at PacketParser.onPacket (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/connection.js:85:12)\n    at PacketParser.executeStart (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/packet_parser.js:75:16)\n    at Socket.<anonymous> (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/connection.js:92:25)\n    at Socket.emit (node:events:513:28)\n    at addChunk (node:internal/streams/readable:324:12)\n    at readableAddChunk (node:internal/streams/readable:297:9)\n    at Readable.push (node:internal/streams/readable:234:10)","code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'street' in 'field list'","sql":"SELECT `id`, `name`, `lastname`, `email`, `password`, `id_number`, `street`, `street_number`, `city`, `country`, `phone`, `created_at`, `updated_at`, `deleted_at` FROM `customers` AS `Customer` WHERE (`Customer`.`deleted_at` IS NULL AND `Customer`.`email` = 'fedegarcia222@gmail.com') LIMIT 1;"},"original":{"type":"Error","message":"Unknown column 'street' in 'field list'","stack":"Error: Unknown column 'street' in 'field list'\n    at Packet.asError (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/packets/packet.js:728:17)\n    at Query.execute (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/commands/command.js:29:26)\n    at Connection.handlePacket (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/connection.js:456:32)\n    at PacketParser.onPacket (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/connection.js:85:12)\n    at PacketParser.executeStart (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/packet_parser.js:75:16)\n    at Socket.<anonymous> (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/connection.js:92:25)\n    at Socket.emit (node:events:513:28)\n    at addChunk (node:internal/streams/readable:324:12)\n    at readableAddChunk (node:internal/streams/readable:297:9)\n    at Readable.push (node:internal/streams/readable:234:10)","code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'street' in 'field list'","sql":"SELECT `id`, `name`, `lastname`, `email`, `password`, `id_number`, `street`, `street_number`, `city`, `country`, `phone`, `created_at`, `updated_at`, `deleted_at` FROM `customers` AS `Customer` WHERE (`Customer`.`deleted_at` IS NULL AND `Customer`.`email` = 'fedegarcia222@gmail.com') LIMIT 1;"},"sql":"SELECT `id`, `name`, `lastname`, `email`, `password`, `id_number`, `street`, `street_number`, `city`, `country`, `phone`, `created_at`, `updated_at`, `deleted_at` FROM `customers` AS `Customer` WHERE (`Customer`.`deleted_at` IS NULL AND `Customer`.`email` = 'fedegarcia222@gmail.com') LIMIT 1;","parameters":{}},"msg":"Unknown column 'street' in 'field list'"}
{"level":30,"time":1691425893801,"pid":52985,"hostname":"flow-Precision-5560","msg":"Error signing JWT"}
{"level":50,"time":1691425893801,"pid":52985,"hostname":"flow-Precision-5560","err":{"type":"Error","message":"invalid expiresIn option for string payload","stack":"Error: invalid expiresIn option for string payload\n    at module.exports [as sign] (/home/flow/dev/fede/app_turnos_js/node_modules/jsonwebtoken/sign.js:152:22)\n    at Object.sign (/home/flow/dev/fede/app_turnos_js/src/domain/services/jwt.js:23:20)\n    at login (/home/flow/dev/fede/app_turnos_js/src/domain/services/authService.js:84:31)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"},"msg":"invalid expiresIn option for string payload"}
{"level":30,"time":1691425939122,"pid":53244,"hostname":"flow-Precision-5560","msg":"Error signing JWT"}
{"level":50,"time":1691425939122,"pid":53244,"hostname":"flow-Precision-5560","err":{"type":"Error","message":"invalid expiresIn option for string payload","stack":"Error: invalid expiresIn option for string payload\n    at module.exports [as sign] (/home/flow/dev/fede/app_turnos_js/node_modules/jsonwebtoken/sign.js:152:22)\n    at Object.sign (/home/flow/dev/fede/app_turnos_js/src/domain/services/jwt.js:23:20)\n    at login (/home/flow/dev/fede/app_turnos_js/src/domain/services/authService.js:84:31)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"},"msg":"invalid expiresIn option for string payload"}
{"level":30,"time":1691425949399,"pid":53319,"hostname":"flow-Precision-5560","msg":"Error signing JWT"}
{"level":50,"time":1691425949399,"pid":53319,"hostname":"flow-Precision-5560","err":{"type":"Error","message":"invalid expiresIn option for string payload","stack":"Error: invalid expiresIn option for string payload\n    at module.exports [as sign] (/home/flow/dev/fede/app_turnos_js/node_modules/jsonwebtoken/sign.js:152:22)\n    at Object.sign (/home/flow/dev/fede/app_turnos_js/src/domain/services/jwt.js:23:20)\n    at login (/home/flow/dev/fede/app_turnos_js/src/domain/services/authService.js:84:31)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"},"msg":"invalid expiresIn option for string payload"}
{"level":30,"time":1691425969773,"pid":53422,"hostname":"flow-Precision-5560","msg":"Error signing JWT"}
{"level":50,"time":1691425969773,"pid":53422,"hostname":"flow-Precision-5560","err":{"type":"Error","message":"invalid expiresIn option for string payload","stack":"Error: invalid expiresIn option for string payload\n    at module.exports [as sign] (/home/flow/dev/fede/app_turnos_js/node_modules/jsonwebtoken/sign.js:152:22)\n    at Object.sign (/home/flow/dev/fede/app_turnos_js/src/domain/services/jwt.js:23:20)\n    at login (/home/flow/dev/fede/app_turnos_js/src/domain/services/authService.js:84:31)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"},"msg":"invalid expiresIn option for string payload"}
{"level":30,"time":1691425970907,"pid":53422,"hostname":"flow-Precision-5560","msg":"Error signing JWT"}
{"level":50,"time":1691425970907,"pid":53422,"hostname":"flow-Precision-5560","err":{"type":"Error","message":"invalid expiresIn option for string payload","stack":"Error: invalid expiresIn option for string payload\n    at module.exports [as sign] (/home/flow/dev/fede/app_turnos_js/node_modules/jsonwebtoken/sign.js:152:22)\n    at Object.sign (/home/flow/dev/fede/app_turnos_js/src/domain/services/jwt.js:23:20)\n    at login (/home/flow/dev/fede/app_turnos_js/src/domain/services/authService.js:84:31)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"},"msg":"invalid expiresIn option for string payload"}
{"level":30,"time":1691425990537,"pid":53532,"hostname":"flow-Precision-5560","msg":"Error signing JWT"}
{"level":50,"time":1691425990537,"pid":53532,"hostname":"flow-Precision-5560","err":{"type":"Error","message":"invalid expiresIn option for string payload","stack":"Error: invalid expiresIn option for string payload\n    at module.exports [as sign] (/home/flow/dev/fede/app_turnos_js/node_modules/jsonwebtoken/sign.js:152:22)\n    at Object.sign (/home/flow/dev/fede/app_turnos_js/src/domain/services/jwt.js:23:20)\n    at login (/home/flow/dev/fede/app_turnos_js/src/domain/services/authService.js:84:31)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"},"msg":"invalid expiresIn option for string payload"}
{"level":50,"time":1694228692853,"pid":18748,"hostname":"flow-Precision-5560","err":{"type":"Error","message":"Error getting appointments for customer with email fedegarcia222@gmail.com","stack":"Error: Error getting appointments for customer with email fedegarcia222@gmail.com\n    at Object.getCustomerAppointments (/home/flow/dev/fede/app_turnos_js/src/infrastructure/services/customerService.js:13:19)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async getCustomerAppointments (/home/flow/dev/fede/app_turnos_js/src/domain/services/customerService.js:5:30)"},"msg":"Error getting appointments for customer with email fedegarcia222@gmail.com"}
{"level":50,"time":1694228716697,"pid":18898,"hostname":"flow-Precision-5560","err":{"type":"Error","message":"Error getting appointments for customer with email fedegarcia222@gmail.com","stack":"Error: Error getting appointments for customer with email fedegarcia222@gmail.com\n    at Object.getCustomerAppointments (/home/flow/dev/fede/app_turnos_js/src/infrastructure/services/customerService.js:14:19)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async getCustomerAppointments (/home/flow/dev/fede/app_turnos_js/src/domain/services/customerService.js:5:30)"},"msg":"Error getting appointments for customer with email fedegarcia222@gmail.com"}
{"level":50,"time":1694228900343,"pid":19839,"hostname":"flow-Precision-5560","err":{"type":"Error","message":"(validateAppointmentNotCreated): Params required","stack":"Error: (validateAppointmentNotCreated): Params required\n    at Object.validateAppointmentNotCreated (/home/flow/dev/fede/app_turnos_js/src/infrastructure/services/appointments.js:60:19)\n    at validateAppointmentDate (/home/flow/dev/fede/app_turnos_js/src/domain/services/appointmentService.js:129:39)\n    at generateAppointments (/home/flow/dev/fede/app_turnos_js/src/domain/services/appointmentService.js:73:40)\n    at createAppointment (/home/flow/dev/fede/app_turnos_js/src/domain/services/appointmentService.js:18:36)\n    at Layer.handle [as handle_request] (/home/flow/dev/fede/app_turnos_js/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/flow/dev/fede/app_turnos_js/node_modules/express/lib/router/route.js:144:13)\n    at validateAddAppointment (/home/flow/dev/fede/app_turnos_js/src/middlewares/appointments.js:7:13)\n    at Layer.handle [as handle_request] (/home/flow/dev/fede/app_turnos_js/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/flow/dev/fede/app_turnos_js/node_modules/express/lib/router/route.js:144:13)\n    at module.exports (/home/flow/dev/fede/app_turnos_js/src/middlewares/validateToken.js:7:13)"},"msg":"(validateAppointmentNotCreated): Params required"}
{"level":50,"time":1694229245576,"pid":20509,"hostname":"flow-Precision-5560","msg":"Bad Request - Parameters Error"}
{"level":50,"time":1694229245576,"pid":20509,"hostname":"flow-Precision-5560"}
{"level":50,"time":1694229336382,"pid":20905,"hostname":"flow-Precision-5560","err":{"type":"Error","message":"(validateAppointmentNotCreated): Params required","stack":"Error: (validateAppointmentNotCreated): Params required\n    at Object.validateAppointmentNotCreated (/home/flow/dev/fede/app_turnos_js/src/infrastructure/services/appointments.js:60:19)\n    at validateAppointmentDate (/home/flow/dev/fede/app_turnos_js/src/domain/services/appointmentService.js:129:39)\n    at generateAppointments (/home/flow/dev/fede/app_turnos_js/src/domain/services/appointmentService.js:73:40)\n    at createAppointment (/home/flow/dev/fede/app_turnos_js/src/domain/services/appointmentService.js:18:36)\n    at Layer.handle [as handle_request] (/home/flow/dev/fede/app_turnos_js/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/flow/dev/fede/app_turnos_js/node_modules/express/lib/router/route.js:144:13)\n    at validateAddAppointment (/home/flow/dev/fede/app_turnos_js/src/middlewares/appointments.js:7:13)\n    at Layer.handle [as handle_request] (/home/flow/dev/fede/app_turnos_js/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/flow/dev/fede/app_turnos_js/node_modules/express/lib/router/route.js:144:13)\n    at module.exports (/home/flow/dev/fede/app_turnos_js/src/middlewares/validateToken.js:7:13)"},"msg":"(validateAppointmentNotCreated): Params required"}
{"level":50,"time":1694230881160,"pid":24749,"hostname":"flow-Precision-5560","err":{"type":"DatabaseError","message":"Referencing column 'customer_id' and referenced column 'id' in foreign key constraint 'appointments_ibfk_1' are incompatible.","stack":"Error\n    at Query.run (/home/flow/dev/fede/app_turnos_js/node_modules/sequelize/lib/dialects/mysql/query.js:52:25)\n    at /home/flow/dev/fede/app_turnos_js/node_modules/sequelize/lib/sequelize.js:315:28\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async MySQLQueryInterface.createTable (/home/flow/dev/fede/app_turnos_js/node_modules/sequelize/lib/dialects/abstract/query-interface.js:98:12)\n    at async Function.sync (/home/flow/dev/fede/app_turnos_js/node_modules/sequelize/lib/model.js:942:7)\n    at async Sequelize.sync (/home/flow/dev/fede/app_turnos_js/node_modules/sequelize/lib/sequelize.js:377:9)","name":"SequelizeDatabaseError","parent":{"type":"Error","message":"Referencing column 'customer_id' and referenced column 'id' in foreign key constraint 'appointments_ibfk_1' are incompatible.","stack":"Error: Referencing column 'customer_id' and referenced column 'id' in foreign key constraint 'appointments_ibfk_1' are incompatible.\n    at Packet.asError (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/packets/packet.js:728:17)\n    at Query.execute (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/commands/command.js:29:26)\n    at Connection.handlePacket (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/connection.js:456:32)\n    at PacketParser.onPacket (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/connection.js:85:12)\n    at PacketParser.executeStart (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/packet_parser.js:75:16)\n    at Socket.<anonymous> (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/connection.js:92:25)\n    at Socket.emit (events.js:315:20)\n    at addChunk (internal/streams/readable.js:309:12)\n    at readableAddChunk (internal/streams/readable.js:284:9)\n    at Socket.Readable.push (internal/streams/readable.js:223:10)","errno":3780,"sqlState":"HY000","sqlMessage":"Referencing column 'customer_id' and referenced column 'id' in foreign key constraint 'appointments_ibfk_1' are incompatible.","sql":"CREATE TABLE IF NOT EXISTS `appointments` (`id` BIGINT auto_increment , `_uuid` VARCHAR(255) NOT NULL, `date` VARCHAR(255) NOT NULL, `hour` VARCHAR(255) NOT NULL, `fraction` VARCHAR(255) NOT NULL, `employee_id` INTEGER NOT NULL, `store_id` INTEGER NOT NULL, `customer_id` INTEGER NOT NULL, `type_id` INTEGER NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;"},"original":{"type":"Error","message":"Referencing column 'customer_id' and referenced column 'id' in foreign key constraint 'appointments_ibfk_1' are incompatible.","stack":"Error: Referencing column 'customer_id' and referenced column 'id' in foreign key constraint 'appointments_ibfk_1' are incompatible.\n    at Packet.asError (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/packets/packet.js:728:17)\n    at Query.execute (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/commands/command.js:29:26)\n    at Connection.handlePacket (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/connection.js:456:32)\n    at PacketParser.onPacket (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/connection.js:85:12)\n    at PacketParser.executeStart (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/packet_parser.js:75:16)\n    at Socket.<anonymous> (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/connection.js:92:25)\n    at Socket.emit (events.js:315:20)\n    at addChunk (internal/streams/readable.js:309:12)\n    at readableAddChunk (internal/streams/readable.js:284:9)\n    at Socket.Readable.push (internal/streams/readable.js:223:10)","errno":3780,"sqlState":"HY000","sqlMessage":"Referencing column 'customer_id' and referenced column 'id' in foreign key constraint 'appointments_ibfk_1' are incompatible.","sql":"CREATE TABLE IF NOT EXISTS `appointments` (`id` BIGINT auto_increment , `_uuid` VARCHAR(255) NOT NULL, `date` VARCHAR(255) NOT NULL, `hour` VARCHAR(255) NOT NULL, `fraction` VARCHAR(255) NOT NULL, `employee_id` INTEGER NOT NULL, `store_id` INTEGER NOT NULL, `customer_id` INTEGER NOT NULL, `type_id` INTEGER NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;"},"sql":"CREATE TABLE IF NOT EXISTS `appointments` (`id` BIGINT auto_increment , `_uuid` VARCHAR(255) NOT NULL, `date` VARCHAR(255) NOT NULL, `hour` VARCHAR(255) NOT NULL, `fraction` VARCHAR(255) NOT NULL, `employee_id` INTEGER NOT NULL, `store_id` INTEGER NOT NULL, `customer_id` INTEGER NOT NULL, `type_id` INTEGER NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;","parameters":{}},"msg":"Referencing column 'customer_id' and referenced column 'id' in foreign key constraint 'appointments_ibfk_1' are incompatible."}
{"level":50,"time":1694230968233,"pid":25114,"hostname":"flow-Precision-5560","err":{"type":"ConnectionError","message":"Unknown database 'negocio'","stack":"SequelizeConnectionError: Unknown database 'negocio'\n    at ConnectionManager.connect (/home/flow/dev/fede/app_turnos_js/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:102:17)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async ConnectionManager._connect (/home/flow/dev/fede/app_turnos_js/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)\n    at async /home/flow/dev/fede/app_turnos_js/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:174:32\n    at async ConnectionManager.getConnection (/home/flow/dev/fede/app_turnos_js/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:197:7)\n    at async /home/flow/dev/fede/app_turnos_js/node_modules/sequelize/lib/sequelize.js:305:26\n    at async MySQLQueryInterface.tableExists (/home/flow/dev/fede/app_turnos_js/node_modules/sequelize/lib/dialects/abstract/query-interface.js:102:17)\n    at async Function.sync (/home/flow/dev/fede/app_turnos_js/node_modules/sequelize/lib/model.js:939:21)\n    at async Sequelize.sync (/home/flow/dev/fede/app_turnos_js/node_modules/sequelize/lib/sequelize.js:377:9)","name":"SequelizeConnectionError","parent":{"type":"Error","message":"Unknown database 'negocio'","stack":"Error: Unknown database 'negocio'\n    at Packet.asError (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/packets/packet.js:728:17)\n    at ClientHandshake.execute (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/commands/command.js:29:26)\n    at Connection.handlePacket (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/connection.js:456:32)\n    at PacketParser.onPacket (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/connection.js:85:12)\n    at PacketParser.executeStart (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/packet_parser.js:75:16)\n    at Socket.<anonymous> (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/connection.js:92:25)\n    at Socket.emit (events.js:315:20)\n    at addChunk (internal/streams/readable.js:309:12)\n    at readableAddChunk (internal/streams/readable.js:284:9)\n    at Socket.Readable.push (internal/streams/readable.js:223:10)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlState":"42000","sqlMessage":"Unknown database 'negocio'"},"original":{"type":"Error","message":"Unknown database 'negocio'","stack":"Error: Unknown database 'negocio'\n    at Packet.asError (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/packets/packet.js:728:17)\n    at ClientHandshake.execute (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/commands/command.js:29:26)\n    at Connection.handlePacket (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/connection.js:456:32)\n    at PacketParser.onPacket (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/connection.js:85:12)\n    at PacketParser.executeStart (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/packet_parser.js:75:16)\n    at Socket.<anonymous> (/home/flow/dev/fede/app_turnos_js/node_modules/mysql2/lib/connection.js:92:25)\n    at Socket.emit (events.js:315:20)\n    at addChunk (internal/streams/readable.js:309:12)\n    at readableAddChunk (internal/streams/readable.js:284:9)\n    at Socket.Readable.push (internal/streams/readable.js:223:10)","code":"ER_BAD_DB_ERROR","errno":1049,"sqlState":"42000","sqlMessage":"Unknown database 'negocio'"}},"msg":"Unknown database 'negocio'"}
{"level":50,"time":1695347460996,"pid":143734,"hostname":"flow-Precision-5560","err":{"type":"Error","message":"Error getting appointments for customer with email [object Object]","stack":"Error: Error getting appointments for customer with email [object Object]\n    at Object.getCustomerAppointments (/home/flow/dev/fede/app_turnos_js/src/infrastructure/services/customerService.js:15:19)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async getCustomerAppointments (/home/flow/dev/fede/app_turnos_js/src/domain/services/customerService.js:5:30)"},"msg":"Error getting appointments for customer with email [object Object]"}
{"level":50,"time":1695347537741,"pid":144144,"hostname":"flow-Precision-5560","err":{"type":"Error","message":"Error getting appointments for customer with email [object Object]","stack":"Error: Error getting appointments for customer with email [object Object]\n    at Object.getCustomerAppointments (/home/flow/dev/fede/app_turnos_js/src/infrastructure/services/customerService.js:15:19)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async getCustomerAppointments (/home/flow/dev/fede/app_turnos_js/src/domain/services/customerService.js:5:30)"},"msg":"Error getting appointments for customer with email [object Object]"}
{"level":50,"time":1695347637214,"pid":144423,"hostname":"flow-Precision-5560","err":{"type":"Error","message":"Error getting appointments for customer with email [object Object]","stack":"Error: Error getting appointments for customer with email [object Object]\n    at Object.getCustomerAppointments (/home/flow/dev/fede/app_turnos_js/src/infrastructure/services/customerService.js:15:19)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async getCustomerAppointments (/home/flow/dev/fede/app_turnos_js/src/domain/services/customerService.js:5:30)"},"msg":"Error getting appointments for customer with email [object Object]"}
{"level":50,"time":1695347737402,"pid":144734,"hostname":"flow-Precision-5560","err":{"type":"Error","message":"Error getting appointments for customer with email undefined","stack":"Error: Error getting appointments for customer with email undefined\n    at Object.getCustomerAppointments (/home/flow/dev/fede/app_turnos_js/src/infrastructure/services/customerService.js:15:19)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async getCustomerAppointments (/home/flow/dev/fede/app_turnos_js/src/domain/services/customerService.js:5:30)"},"msg":"Error getting appointments for customer with email undefined"}
{"level":50,"time":1695347746054,"pid":144789,"hostname":"flow-Precision-5560","err":{"type":"Error","message":"Error getting appointments for customer with email undefined","stack":"Error: Error getting appointments for customer with email undefined\n    at Object.getCustomerAppointments (/home/flow/dev/fede/app_turnos_js/src/infrastructure/services/customerService.js:15:19)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async getCustomerAppointments (/home/flow/dev/fede/app_turnos_js/src/domain/services/customerService.js:5:30)"},"msg":"Error getting appointments for customer with email undefined"}
{"level":50,"time":1695350172108,"pid":148320,"hostname":"flow-Precision-5560","msg":"Route not found"}
{"level":50,"time":1695350172109,"pid":148320,"hostname":"flow-Precision-5560"}
{"level":50,"time":1695350247937,"pid":148460,"hostname":"flow-Precision-5560","msg":"Route not found"}
{"level":50,"time":1695350316685,"pid":148582,"hostname":"flow-Precision-5560","msg":"Route not found"}
{"level":50,"time":1695350316685,"pid":148582,"hostname":"flow-Precision-5560"}
{"level":50,"time":1695350359991,"pid":148684,"hostname":"flow-Precision-5560","err":{"type":"ReferenceError","message":"store_id is not defined","stack":"ReferenceError: store_id is not defined\n    at getStoreEmployees (/home/flow/dev/fede/app_turnos_js/src/domain/services/storeService.js:6:9)\n    at Layer.handle [as handle_request] (/home/flow/dev/fede/app_turnos_js/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/flow/dev/fede/app_turnos_js/node_modules/express/lib/router/route.js:144:13)\n    at module.exports (/home/flow/dev/fede/app_turnos_js/src/middlewares/validateToken.js:7:13)\n    at Layer.handle [as handle_request] (/home/flow/dev/fede/app_turnos_js/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/flow/dev/fede/app_turnos_js/node_modules/express/lib/router/route.js:144:13)\n    at Route.dispatch (/home/flow/dev/fede/app_turnos_js/node_modules/express/lib/router/route.js:114:3)\n    at Layer.handle [as handle_request] (/home/flow/dev/fede/app_turnos_js/node_modules/express/lib/router/layer.js:95:5)\n    at /home/flow/dev/fede/app_turnos_js/node_modules/express/lib/router/index.js:284:15\n    at param (/home/flow/dev/fede/app_turnos_js/node_modules/express/lib/router/index.js:365:14)"},"msg":"store_id is not defined"}
{"level":50,"time":1695350447072,"pid":148821,"hostname":"flow-Precision-5560","err":{"type":"ReferenceError","message":"store_id is not defined","stack":"ReferenceError: store_id is not defined\n    at getStoreEmployees (/home/flow/dev/fede/app_turnos_js/src/domain/services/storeService.js:6:9)\n    at Layer.handle [as handle_request] (/home/flow/dev/fede/app_turnos_js/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/flow/dev/fede/app_turnos_js/node_modules/express/lib/router/route.js:144:13)\n    at module.exports (/home/flow/dev/fede/app_turnos_js/src/middlewares/validateToken.js:7:13)\n    at Layer.handle [as handle_request] (/home/flow/dev/fede/app_turnos_js/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/flow/dev/fede/app_turnos_js/node_modules/express/lib/router/route.js:144:13)\n    at Route.dispatch (/home/flow/dev/fede/app_turnos_js/node_modules/express/lib/router/route.js:114:3)\n    at Layer.handle [as handle_request] (/home/flow/dev/fede/app_turnos_js/node_modules/express/lib/router/layer.js:95:5)\n    at /home/flow/dev/fede/app_turnos_js/node_modules/express/lib/router/index.js:284:15\n    at param (/home/flow/dev/fede/app_turnos_js/node_modules/express/lib/router/index.js:365:14)"},"msg":"store_id is not defined"}
